# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: PR

permissions:
  contents: read

on:
  pull_request:

env:
  GOLANGCI_LINT_VERSION: 'v2.1.6'

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      go: ${{ steps.filter.outputs.go }}
    steps:
      # For pull requests it's not necessary checkout the code
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            go:
              - '**/*.go'
              - '**/*.mod'
              - '**/*.sum'
              - '.golangci.yml'

  detect-modules:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable
          cache-dependency-path: |
            **/go.sum
            go.sum
      - id: set-modules
        run: echo modules=$(echo $(go list -m -json) | jq -s '.' | jq -c '[.[].Dir]') >> $GITHUB_OUTPUT

  tidy:
    name: tidy
    needs: detect-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          cache-dependency-path: 'go.sum'
          go-version: stable
      - name: Run tidy
        working-directory: ${{ matrix.modules }}
        run: go mod tidy --diff

  checks:
    name: checks
    needs: detect-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
        go-version: [ oldstable, stable ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          cache-dependency-path: 'go.sum'
          go-version: ${{ matrix.go-version }}
      - name: Run Download
        working-directory: ${{ matrix.modules }}
        run: go mod download
      - name: Run govulncheck
        working-directory: ${{ matrix.modules }}
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@v0.0.0-20250106192626-d1f380186385 # v1.1.4
          govulncheck -show verbose ./...

  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Spell Check Repo
        uses: crate-ci/typos@b1ae8d918b6e85bd611117d3d9a3be4f903ee5e4 # v1.33.1

  golangci:
    name: lint
    needs: detect-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable
          cache-dependency-path: 'go.sum'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: ${{ env.GOLANGCI_LINT_VERSION }}

          # Optional: working directory, useful for monorepos
          # working-directory: headers
          working-directory: ${{ matrix.modules }}

          # Optional: golangci-lint command line arguments.
          #
          # Note: By default, the `.golangci.yml` file should be at the root of the repository.
          # The location of the configuration file can be changed by using `--config=`
          args: --timeout=20m --output.sarif.path="${{ matrix.modules }}/results.sarif"

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true, then all caching functionality will be completely disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true, then the action won't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true, then the action won't cache or restore ~/.cache/go-build.
          # skip-build-cache: true

          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          # install-mode: "goinstall"
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@39edc492dbe16b1465b0cafca41432d857bdb31a # v3.29.1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: "${{ matrix.modules }}/results.sarif"
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: golangci-lint

  tests:
    name: tests
    needs: detect-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ oldstable, stable ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: |
            **/go.sum
            go.sum

      - name: Test package
        run: go test -v -gcflags=-l ./... -race -coverprofile=./cover.out -covermode=atomic

      - name: Check conf package coverage
        uses: vladopajic/go-test-coverage@ebf1fb6f7267bd290a83cc16f535067b51fd1d0b # v2.15.0
        with:
          profile: ./cover.out
          local-prefix: github.com/nafigator/zap-net-sink
          threshold-file: 10
          threshold-package: 10
          threshold-total: 10

      - name: Upload headers coverage to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cover.out
          flags: unittests
          name: codecov-zap-net-sink
          verbose: false
